apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: DockerHub-registry
      containers:
      - name: frontend
        image: 5464534563/webapp-demo:v17
        imagePullPolicy: Always
#        env:
#          - name: REACT_APP_BACKEND_URL
#            value: "http://hello.fealtytechnologies.com/api/tasks"
        ports:
        - containerPort: 8080
        resources:  # Correct indentation for resources
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"


---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: Loadbalancer
  selector:
    role: frontend



