apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: DockerHub-registry
      containers:
      - name: frontend
        image: 5464534563/webapp-demo:v35
        imagePullPolicy: Always
#        env:
#          - name: REACT_APP_BACKEND_URL
#            value: "http://hello.fealtytechnologies.com/api/tasks"
        ports:
        - containerPort: 8080
        resources:  # Correct indentation for resources
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"


---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: Loadbalancer
  selector:
    role: frontend

---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: three-tier
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Test@123"
        - name: MYSQL_DATABASE
          value: "bankappdb"
        ports:
        - containerPort: 3306
          name: mysql
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: three-tier
spec:
  ports:
  - port: 3306
  selector:
    app: mysql

